## Use coeficientes CL e Cd From Qblade

In [31]:
import pandas as pd
import sys
import csv

print(sys.version)
print('pandas version', pd.__version__)

3.10.12 | packaged by conda-forge | (main, Jun 23 2023, 22:40:32) [GCC 12.3.0]
pandas version 2.0.3

In [ ]:
 # /kaggle/input/polar-try/E63 # V11

## Reading from files ( No edit from Qblade )

In [32]:
## Carregar banco de dados 

df_cd = pd.read_csv("/kaggle/input/polar-try/E63/esconde_geim/all_cd.txt",delimiter='\t',skiprows=2)
df_cl = pd.read_csv("/kaggle/input/polar-try/E63/esconde_geim/all_cl.txt",delimiter='\t',skiprows=2)
#/kaggle/input/polar-try/Clark Y/esconde_geim/all_cd.txt
#df2 = pd.read_csv("/kaggle/input/polar-try/Clark Y/cl/cl_R_4.5e4.txt",delimiter='\t', skiprows=1, usecols=['Angle of Attack [deg]', 'Lift Coefficient Cl [-]'])
#df3 = pd.read_csv("/kaggle/input/polar-try/Clark Y/cl/cl_R_1e5.txt",delimiter='\t', skiprows=2, usecols=['Angle of Attack [deg]', 'Lift Coefficient Cl [-]'])
#df4 = pd.read_csv("/kaggle/input/polar-try/Clark Y/cd/cd_R_4.5e4.txt",delimiter='\t', skiprows=1)
#df_temp = pd.read_csv('arquivo.csv', nrows=0)
#print(df2.columns)
#df2.head(12)
#df2['cl_next'] = df3.iloc[:, 1]

#print(df.columns)
#df_cl.head(6)
#df_cd.head(12)

print('done')
#df2.head(12)
#/kaggle/input/polar-try/E63

done

In [33]:
# Garante que pandas mostre todas as linhas e colunas sem cortar

#pd.set_option('display.max_rows', None)
#pd.set_option('display.max_colwidth', None)

pd.reset_option('display.max_rows')
pd.reset_option('display.max_colwidth')

print(df_cl.iloc[:, [0]])

    Angle of Attack [deg]
0          -1.8000000e+02
1          -1.7900000e+02
2          -1.7800000e+02
3          -1.7700000e+02
4          -1.7600000e+02
..                    ...
363                   END
364                   END
365                   END
366                   END
367                   END

[368 rows x 1 columns]

In [34]:
# Remover colunas desnecessárias 

columns_to_drop_cd = [
    'Angle of Attack [deg].1',
    'Angle of Attack [deg].2',
    'Angle of Attack [deg].3',
    'Angle of Attack [deg].4',
    'Angle of Attack [deg].5',
    'Angle of Attack [deg].6',
    'Angle of Attack [deg].7',
    'Angle of Attack [deg].8',
    'Drag Coefficient Cd [-].8'
]
#Drag Coefficient Cd [-].8
columns_to_drop_cl = [
    'Angle of Attack [deg].1',
    'Angle of Attack [deg].2',
    'Angle of Attack [deg].3',
    'Angle of Attack [deg].4',
    'Angle of Attack [deg].5',
    'Angle of Attack [deg].6',
    'Angle of Attack [deg].7',
    'Angle of Attack [deg].8',
    'Lift Coefficient Cl [-].8'
]
 
df_cl = df_cl.drop(columns=columns_to_drop_cl, errors='ignore')
df_cd = df_cd.drop(columns=columns_to_drop_cd, errors='ignore')

# Remover linhas desnecessárias 
df_cl = df_cl[df_cl.iloc[:, 0] != 'END']
df_cd = df_cd[df_cd.iloc[:, 0] != 'END']

print( 'done')

done

In [35]:
# testar de vieram certo
#df_cl.head(360)
df_cd.head(400)

,Angle of Attack [deg],Drag Coefficient Cd [-],Drag Coefficient Cd [-].1,Drag Coefficient Cd [-].2,Drag Coefficient Cd [-].3,Drag Coefficient Cd [-].4,Drag Coefficient Cd [-].5,Drag Coefficient Cd [-].6,Drag Coefficient Cd [-].7
0,-1.8000000e+02,6.0000080e-03,6.0000010e-03,6.0000019e-03,6.0000028e-03,6.0000038e-03,0.006000,6.0000080e-03,6.0000047e-03
1,-1.7900000e+02,6.5383455e-03,6.5383385e-03,6.5383399e-03,6.5383408e-03,6.5383413e-03,0.006538,6.5383450e-03,6.5383422e-03
2,-1.7800000e+02,8.1510311e-03,8.1510255e-03,8.1510264e-03,8.1510274e-03,8.1510274e-03,0.008151,8.1510311e-03,8.1510283e-03
3,-1.7700000e+02,1.0833598e-02,1.0833595e-02,1.0833595e-02,1.0833596e-02,1.0833596e-02,0.010834,1.0833598e-02,1.0833597e-02
4,-1.7600000e+02,1.4580285e-02,1.4580285e-02,1.4580285e-02,1.4580285e-02,1.4580285e-02,0.014580,1.4580285e-02,1.4580285e-02
...,...,...,...,...,...,...,...,...,...
353,1.7600000e+02,1.4633652e-02,8.1577078e-03,END,6.5391739e-03,END,0.110635,1.0856132e-02,6.0000001e-03
354,1.7700000e+02,1.0856133e-02,6.5391739e-03,END,6.0000005e-03,END,0.096402,8.1577078e-03,END
355,1.7800000e+02,8.1577096e-03,6.0000005e-03,END,END,END,0.083167,6.5391734e-03,END
356,1.7900000e+02,6.5391758e-03,END,END,END,END,0.070945,6.0000001e-03,END
357,1.8000000e+02,6.0000024e-03,END,END,END,END,0.059748,END,END

In [ ]:
#quando o numero de rows =360, falta 1
# de -180 a +180 uma a 1 contando zero, tem 361 elementos

In [36]:
# remover pontas desnecessárias 

# aoenas 1 vez 

df_cl = df_cl.iloc[90:-89].reset_index(drop=True)
df_cd = df_cd.iloc[90:-89].reset_index(drop=True)

print('done')

done

In [37]:
# testar se removera certo

df_cd.head(181)
#df_cd.head(181)

,Angle of Attack [deg],Drag Coefficient Cd [-],Drag Coefficient Cd [-].1,Drag Coefficient Cd [-].2,Drag Coefficient Cd [-].3,Drag Coefficient Cd [-].4,Drag Coefficient Cd [-].5,Drag Coefficient Cd [-].6,Drag Coefficient Cd [-].7
0,-9.0000000e+01,1.6961665e+00,1.6961962e+00,1.6961921e+00,1.6961887e+00,1.6961851e+00,1.696170,1.6961645e+00,1.6961803e+00
1,-8.9000000e+01,1.6956620e+00,1.6956933e+00,1.6956890e+00,1.6956854e+00,1.6956816e+00,1.695666,1.6956599e+00,1.6956766e+00
2,-8.8000000e+01,1.6941524e+00,1.6941851e+00,1.6941806e+00,1.6941769e+00,1.6941730e+00,1.694156,1.6941500e+00,1.6941676e+00
3,-8.7000000e+01,1.6916393e+00,1.6916738e+00,1.6916690e+00,1.6916651e+00,1.6916609e+00,1.691643,1.6916366e+00,1.6916553e+00
4,-8.6000000e+01,1.6881256e+00,1.6881618e+00,1.6881568e+00,1.6881527e+00,1.6881484e+00,1.688129,1.6881226e+00,1.6881424e+00
...,...,...,...,...,...,...,...,...,...
174,8.7000000e+01,1.8482418e+00,1.8528447e+00,1.8482527e+00,1.8534193e+00,1.8482505e+00,1.757959,1.8511221e+00,1.8528451e+00
175,8.8000000e+01,1.8511120e+00,1.8534194e+00,1.8442402e+00,1.8528446e+00,1.8442382e+00,1.771857,1.8528455e+00,1.8511218e+00
176,8.9000000e+01,1.8528358e+00,1.8528448e+00,1.8390902e+00,1.8511214e+00,1.8390882e+00,1.784710,1.8534201e+00,1.8482522e+00
177,9.0000000e+01,1.8534108e+00,1.8511217e+00,1.8328091e+00,1.8482518e+00,1.8328072e+00,1.796500,1.8528455e+00,1.8442398e+00
178,9.1000000e+01,1.8528367e+00,1.8482521e+00,1.8254050e+00,1.8442395e+00,1.8254032e+00,1.807214,1.8511223e+00,1.8390898e+00

podemos ver assim quantas linhas faltam

## Obter linhas que faltam

In [38]:
df_cd.iloc[80:110]



# falta E63
# 9 dgr , linha 99 --> igual a de baixo
# 13 dgr , linha 102 --> igual a de baixo
# 14 dgr , linha 103 --> igual a de cima

# falta MH112
# -1 dgr linha 89 --> igual a de baixo

,Angle of Attack [deg],Drag Coefficient Cd [-],Drag Coefficient Cd [-].1,Drag Coefficient Cd [-].2,Drag Coefficient Cd [-].3,Drag Coefficient Cd [-].4,Drag Coefficient Cd [-].5,Drag Coefficient Cd [-].6,Drag Coefficient Cd [-].7
80,-1.0000000e+01,1.2375304e-02,5.8377989e-02,5.6545537e-02,5.3094864e-02,4.0095400e-02,0.012127,1.2126772e-02,1.5380544e-02
81,-9.0000000e+00,1.2116054e-02,4.8330728e-02,4.5960356e-02,4.1344389e-02,2.6147069e-02,0.012114,1.2114095e-02,1.2466346e-02
82,-8.0000000e+00,1.2101417e-02,3.9259769e-02,3.6177997e-02,3.0300612e-02,1.6713338e-02,0.012101,1.2101417e-02,1.2104679e-02
83,-7.0000000e+00,1.2088740e-02,3.1178167e-02,2.7270120e-02,2.0860136e-02,1.2865704e-02,0.012089,1.2088740e-02,1.2088740e-02
84,-6.0000000e+00,1.2076063e-02,2.4119090e-02,1.9659447e-02,1.4738824e-02,1.2112495e-02,0.012076,1.2076063e-02,1.2076063e-02
85,-5.0000000e+00,1.2063386e-02,1.8194012e-02,1.4420518e-02,1.2432552e-02,1.2063386e-02,0.012063,1.2063386e-02,1.2063386e-02
86,-4.0000000e+00,5.5070002e-02,8.3339997e-02,8.0890000e-02,7.9559997e-02,7.1079999e-02,0.012051,1.2050709e-02,5.1279999e-02
87,-3.0000000e+00,5.4749999e-02,7.1520001e-02,6.8080001e-02,6.8860002e-02,5.3029999e-02,0.012038,1.2038032e-02,5.2700001e-03
88,-2.0000000e+00,5.8070000e-02,5.9510000e-02,2.5250001e-02,5.0940000e-02,3.5270002e-02,0.012025,1.2025354e-02,4.5200000e-03
89,-1.0000000e+00,4.9160000e-02,2.8190000e-02,2.2280000e-02,2.3530001e-02,2.2650000e-02,0.014760,1.2012677e-02,9.6300002e-03
90,0.0000000e+00,3.4820002e-02,2.5110001e-02,2.5760001e-02,2.1070000e-02,1.4520000e-02,0.010480,6.0999999e-03,1.0640000e-02
91,1.0000000e+00,3.1780001e-02,2.8279999e-02,2.8570000e-02,2.3119999e-02,1.1370000e-02,0.007530,5.0200000e-03,1.2160000e-02
92,2.0000000e+00,3.4680001e-02,3.2790001e-02,2.6860001e-02,1.9810000e-02,8.8200001e-03,0.007240,9.2799999e-03,1.6060000e-02
93,3.0000000e+00,3.8649999e-02,3.9329998e-02,2.0260001e-02,1.6340001e-02,1.1990000e-02,0.006630,1.0380000e-02,2.3050001e-02
94,4.0000000e+00,4.4240002e-02,3.9799999e-02,6.3239999e-02,2.7670000e-02,1.7969999e-02,0.008300,1.2830000e-02,4.0830001e-02
95,5.0000000e+00,5.2239999e-02,2.7240001e-02,8.2719997e-02,6.2199999e-02,3.5730001e-02,0.009040,1.4930000e-02,1.4927000e-01
96,6.0000000e+00,6.3720003e-02,4.5480002e-02,1.9580001e-01,1.7129000e-01,5.4740001e-02,0.009880,2.6219999e-02,9.5391952e-02
97,7.0000000e+00,8.0329999e-02,7.1259998e-02,2.7625999e-01,9.5375277e-02,2.6945001e-01,0.011100,4.2810000e-02,1.0993449e-01
98,8.0000000e+00,7.7629998e-02,2.0062999e-01,1.5901622e-01,1.0989483e-01,1.5853849e-01,0.012840,6.4450003e-02,1.2534192e-01
99,1.0000000e+01,1.2932000e-01,2.2788000e-01,1.7710668e-01,1.2529637e-01,1.7671494e-01,0.014620,1.8235999e-01,1.4164969e-01
100,1.1000000e+01,1.6147000e-01,1.2553161e-01,1.9609937e-01,1.4160486e-01,1.9577312e-01,0.016060,1.1007077e-01,1.5886681e-01
101,1.2000000e+01,1.8533000e-01,1.4177622e-01,2.1597530e-01,1.5882511e-01,2.1569996e-01,0.018680,1.2546112e-01,1.7698900e-01
102,1.5000000e+01,2.4976000e-01,1.5895370e-01,2.3671347e-01,1.7695116e-01,2.3647840e-01,0.024910,1.4175108e-01,1.9600467e-01
103,1.6000000e+01,1.3862933e-01,1.7705007e-01,2.5829127e-01,1.9597067e-01,2.5808856e-01,0.030440,1.5895255e-01,2.1589771e-01
104,1.7000000e+01,1.5651233e-01,1.9604839e-01,2.8068468e-01,2.1586727e-01,2.8050831e-01,0.037570,1.7706171e-01,2.3664893e-01
105,1.8000000e+01,1.7511286e-01,2.1592945e-01,3.0386832e-01,2.3662168e-01,3.0371371e-01,0.046350,1.9606669e-01,2.5823686e-01
106,1.9000000e+01,1.9448113e-01,2.3667221e-01,3.2781577e-01,2.5821245e-01,3.2767922e-01,0.056110,2.1595098e-01,2.8063828e-01
107,2.0000000e+01,2.1464019e-01,2.5825405e-01,3.5249934e-01,2.8061634e-01,3.5237804e-01,0.065340,2.3669501e-01,3.0382839e-01
108,2.1000000e+01,2.3559627e-01,2.8065103e-01,3.7789038e-01,3.0380863e-01,3.7778202e-01,0.072530,2.5827703e-01,3.2778105e-01
109,2.2000000e+01,2.5734484e-01,3.0383784e-01,4.0395927e-01,3.2776320e-01,4.0386197e-01,0.171150,2.8067350e-01,3.5246894e-01

In [ ]:
# pular para rascunho  para teste de interpolaçao

## TRATAMENTO PARA MH112

In [ ]:
# implementando outra interpolação CL

# try gpt 
# começa apartir de (Obter linhas que faltam)
# Lê o arquivo CSV em um DataFrame
df = df_cl
#df.iloc[80:91]
#df.head(400)
# Pega as linhas acima e abaixo da linha 88
linha_acima = df.iloc[88]
linha_abaixo = df.iloc[89]


# Inicializa uma nova linha interpolada
linha_interpolada = {}

# Para cada coluna
for coluna in df.columns:
    valor_acima = linha_acima[coluna]
    valor_abaixo = linha_abaixo[coluna]

    # Tenta converter para float e fazer interpolação
    try:
        valor_interp = round((float(valor_acima) + float(valor_abaixo)) / 2, 8)
        #valor_interp = (float(valor_acima) + float(valor_abaixo)) / 2
    except ValueError:
        # Se não for numérico (ex: texto), coloca um valor nulo ou preserva o de cima
        valor_interp = None  # ou use: valor_acima

    linha_interpolada[coluna] = valor_interp

# Converte para DataFrame
linha_interpolada_df = pd.DataFrame([linha_interpolada])

# Insere a nova linha na posição 88
df_novo = pd.concat([df.iloc[:89], linha_interpolada_df, df.iloc[89:]]).reset_index(drop=True)
#df_novo
#df_novo.iloc[80:91]
# Salva o novo arquivo
df_cl = df_novo

In [ ]:
# implementando outra interpolação CD

# try gpt 
# começa apartir de (Obter linhas que faltam)
# Lê o arquivo CSV em um DataFrame
df = df_cd
#df.iloc[80:91]
#df.head(400)
# Pega as linhas acima e abaixo da linha 88
linha_acima = df.iloc[88]
linha_abaixo = df.iloc[89]


# Inicializa uma nova linha interpolada
linha_interpolada = {}

# Para cada coluna
for coluna in df.columns:
    valor_acima = linha_acima[coluna]
    valor_abaixo = linha_abaixo[coluna]

    # Tenta converter para float e fazer interpolação
    try:
        valor_interp = round((float(valor_acima) + float(valor_abaixo)) / 2, 8)
        #valor_interp = (float(valor_acima) + float(valor_abaixo)) / 2
    except ValueError:
        # Se não for numérico (ex: texto), coloca um valor nulo ou preserva o de cima
        valor_interp = None  # ou use: valor_acima

    linha_interpolada[coluna] = valor_interp

# Converte para DataFrame
linha_interpolada_df = pd.DataFrame([linha_interpolada])

# Insere a nova linha na posição 88
df_novo = pd.concat([df.iloc[:89], linha_interpolada_df, df.iloc[89:]]).reset_index(drop=True)

#df_novo
#df_novo.iloc[80:91]
# Salva o novo arquivo
df_cd = df_novo

## TRATAMENTO PARA MH116

In [ ]:
## alterações em CL

# alterar incorreto cl 9 
#import pandas as pd
# add a line between line 97 and 98 that is the same as line 97

# Supondo que 'df' é o seu DataFrame

# Separar o topo, a linha a duplicar, e o restante
top = df_cl.iloc[:99]                      # inclui até a linha 98
duplicate_row = df_cl.iloc[[98]].copy()   # linha 97 (como DataFrame)
bottom = df_cl.iloc[99:]                  # da linha 98 em diante

# Concatenar tudo
df_cl = pd.concat([top, duplicate_row, bottom]).reset_index(drop=True)
# alterar valor do grau 9 
df_cl.iloc[99, 0] = 9.0000000e+00

# alterar incorreto cl 10
#import pandas as pd
# add a line between line 97 and 98 that is the same as line 97

# Supondo que 'df' é o seu DataFrame

# Separar o topo, a linha a duplicar, e o restante
top = df_cl.iloc[:100]                      # inclui até a linha 90
duplicate_row = df_cl.iloc[[100]].copy()   # linha 100 (como DataFrame)
bottom = df_cl.iloc[100:]                  # da linha 100 em diante

# Concatenar tudo
df_cl = pd.concat([top, duplicate_row, bottom]).reset_index(drop=True)
# alterar valor do grau 9 
df_cl.iloc[100, 0] = 1.0000000e+01




# show 

df_cl.iloc[95:110]

In [ ]:
## alterações em CD

# alterar incorreto cd 9 
#import pandas as pd
# add a line between line 97 and 98 that is the same as line 97

# Supondo que 'df' é o seu DataFrame

# Separar o topo, a linha a duplicar, e o restante
top = df_cd.iloc[:99]                      # inclui até a linha 98
duplicate_row = df_cd.iloc[[98]].copy()   # linha 97 (como DataFrame)
bottom = df_cd.iloc[99:]                  # da linha 98 em diante

# Concatenar tudo
df_cd = pd.concat([top, duplicate_row, bottom]).reset_index(drop=True)
# alterar valor do grau 9 
df_cd.iloc[99, 0] = 9.0000000e+00

# alterar incorreto cl 10
#import pandas as pd
# add a line between line 97 and 98 that is the same as line 97

# Supondo que 'df' é o seu DataFrame

# Separar o topo, a linha a duplicar, e o restante
top = df_cd.iloc[:100]                      # incdui até a linha 90
duplicate_row = df_cd.iloc[[100]].copy()   # linha 100 (como DataFrame)
bottom = df_cd.iloc[100:]                  # da linha 100 em diante

# Concatenar tudo
df_cd = pd.concat([top, duplicate_row, bottom]).reset_index(drop=True)
# alterar valor do grau 9 
df_cd.iloc[100, 0] = 1.0000000e+01




# show 

df_cd.iloc[95:110]

## TRATAMENTO PARA E63

In [39]:
# implementando outra interpolação CL

# try gpt 
# começa apartir de (Obter linhas que faltam)
# Lê o arquivo CSV em um DataFrame
df = df_cl
#df.iloc[80:91]
#df.head(400)


### alterar incorreto cl 9 

# Pega as linhas acima e abaixo da linha 98
# Pega as linhas acima e abaixo da linha 98
linha_acima = df.iloc[98]
linha_abaixo = df.iloc[99]


# Inicializa uma nova linha interpolada
linha_interpolada = {}

# Para cada coluna
for coluna in df.columns:
    valor_acima = linha_acima[coluna]
    valor_abaixo = linha_abaixo[coluna]

    # Tenta converter para float e fazer interpolação
    try:
        valor_interp = round((float(valor_acima) + float(valor_abaixo)) / 2, 8)
        #valor_interp = (float(valor_acima) + float(valor_abaixo)) / 2
    except ValueError:
        # Se não for numérico (ex: texto), coloca um valor nulo ou preserva o de cima
        valor_interp = None  # ou use: valor_acima

    linha_interpolada[coluna] = valor_interp

# Converte para DataFrame
linha_interpolada_df = pd.DataFrame([linha_interpolada])

# Insere a nova linha na posição 88
df_novo = pd.concat([df.iloc[:99], linha_interpolada_df, df.iloc[99:]]).reset_index(drop=True)
#df_novo
#df_novo.iloc[80:91]
# Salva o novo arquivo
df_cl = df_novo

# alterar incorreto cl 13 

#import pandas as pd
# add a line between line 97 and 98 that is the same as line 97

# Supondo que 'df' é o seu DataFrame

# Separar o topo, a linha a duplicar, e o restante
top = df_cl.iloc[:103]                      # inclui até a linha 97
duplicate_row = df_cl.iloc[[102]].copy()   # linha 97 (como DataFrame)
bottom = df_cl.iloc[103:]                  # da linha 98 em diante

# Concatenar tudo
df_cl = pd.concat([top, duplicate_row, bottom]).reset_index(drop=True)
# alterar valor do grau 9 
df_cl.iloc[103, 0] = 1.3000000e+01
#print('done')


### alterar incorreto cl 14 
df = df_cl
# Pega as linhas acima e abaixo da linha 103
# Pega as linhas acima e abaixo da linha 
linha_acima = df.iloc[103]
linha_abaixo = df.iloc[104]


# Inicializa uma nova linha interpolada
linha_interpolada = {}

# Para cada coluna
for coluna in df.columns:
    valor_acima = linha_acima[coluna]
    valor_abaixo = linha_abaixo[coluna]

    # Tenta converter para float e fazer interpolação
    try:
        valor_interp = round((float(valor_acima) + float(valor_abaixo)) / 2, 8)
        #valor_interp = (float(valor_acima) + float(valor_abaixo)) / 2
    except ValueError:
        # Se não for numérico (ex: texto), coloca um valor nulo ou preserva o de cima
        valor_interp = None  # ou use: valor_acima

    linha_interpolada[coluna] = valor_interp

# Converte para DataFrame
linha_interpolada_df = pd.DataFrame([linha_interpolada])

# Insere a nova linha na posição 88
df_novo = pd.concat([df.iloc[:104], linha_interpolada_df, df.iloc[104:]]).reset_index(drop=True)
#df_novo
#df_novo.iloc[80:91]
# Salva o novo arquivo
df_cl = df_novo
print('done')
##

done

In [40]:
# implementando outra interpolação Cd

# try gpt 
# começa apartir de (Obter linhas que faltam)
# Lê o arquivo CSV em um DataFrame
df = df_cd
#df.iloc[80:91]
#df.head(400)


### alterar incorreto cl 9 

# Pega as linhas acima e abaixo da linha 98
# Pega as linhas acima e abaixo da linha 98
linha_acima = df.iloc[98]
linha_abaixo = df.iloc[99]


# Inicializa uma nova linha interpolada
linha_interpolada = {}

# Para cada coluna
for coluna in df.columns:
    valor_acima = linha_acima[coluna]
    valor_abaixo = linha_abaixo[coluna]

    # Tenta converter para float e fazer interpolação
    try:
        valor_interp = round((float(valor_acima) + float(valor_abaixo)) / 2, 8)
        #valor_interp = (float(valor_acima) + float(valor_abaixo)) / 2
    except ValueError:
        # Se não for numérico (ex: texto), coloca um valor nulo ou preserva o de cima
        valor_interp = None  # ou use: valor_acima

    linha_interpolada[coluna] = valor_interp

# Converte para DataFrame
linha_interpolada_df = pd.DataFrame([linha_interpolada])

# Insere a nova linha na posição 88
df_novo = pd.concat([df.iloc[:99], linha_interpolada_df, df.iloc[99:]]).reset_index(drop=True)
#df_novo
#df_novo.iloc[80:91]
# Salva o novo arquivo
df_cd = df_novo

# alterar incorreto cl 13 

#import pandas as pd
# add a line between line 97 and 98 that is the same as line 97

# Supondo que 'df' é o seu DataFrame

# Separar o topo, a linha a duplicar, e o restante
top = df_cd.iloc[:103]                      # inclui até a linha 97
duplicate_row = df_cd.iloc[[102]].copy()   # linha 97 (como DataFrame)
bottom = df_cd.iloc[103:]                  # da linha 98 em diante

# Concatenar tudo
df_cd = pd.concat([top, duplicate_row, bottom]).reset_index(drop=True)
# alterar valor do grau 9 
df_cd.iloc[103, 0] = 1.3000000e+01
#print('done')


### alterar incorreto cl 14 
df = df_cd
# Pega as linhas acima e abaixo da linha 103
# Pega as linhas acima e abaixo da linha 
linha_acima = df.iloc[103]
linha_abaixo = df.iloc[104]


# Inicializa uma nova linha interpolada
linha_interpolada = {}

# Para cada coluna
for coluna in df.columns:
    valor_acima = linha_acima[coluna]
    valor_abaixo = linha_abaixo[coluna]

    # Tenta converter para float e fazer interpolação
    try:
        valor_interp = round((float(valor_acima) + float(valor_abaixo)) / 2, 8)
        #valor_interp = (float(valor_acima) + float(valor_abaixo)) / 2
    except ValueError:
        # Se não for numérico (ex: texto), coloca um valor nulo ou preserva o de cima
        valor_interp = None  # ou use: valor_acima

    linha_interpolada[coluna] = valor_interp

# Converte para DataFrame
linha_interpolada_df = pd.DataFrame([linha_interpolada])

# Insere a nova linha na posição 88
df_novo = pd.concat([df.iloc[:104], linha_interpolada_df, df.iloc[104:]]).reset_index(drop=True)
#df_novo
#df_novo.iloc[80:91]
# Salva o novo arquivo
df_cd = df_novo
print('done')
##

done

In [ ]:
# alterar incorreto cl 14

In [42]:
# Garante que pandas mostre todas as linhas e colunas sem cortar

#pd.set_option('display.max_rows', None)
#pd.set_option('display.max_colwidth', None)

pd.reset_option('display.max_rows')
pd.reset_option('display.max_colwidth')

print(df_cl.iloc[:, [0]])

    Angle of Attack [deg]
0          -9.0000000e+01
1          -8.9000000e+01
2          -8.8000000e+01
3          -8.7000000e+01
4          -8.6000000e+01
..                    ...
177         8.7000000e+01
178         8.8000000e+01
179         8.9000000e+01
180         9.0000000e+01
181         9.1000000e+01

[182 rows x 1 columns]

## Save files

In [44]:
# Save files

df_cl.to_csv('cl.txt', index=False, header=False, sep='\t')
df_cd.to_csv('cd.txt', index=False, header=False, sep='\t')
print('done')

done

## Rascunhos

uma vez que a maioreia dos exemplos clonando linhas apresenta erro na interpolação, faz-se necessario modificar o método de tratamento das matrizes de cl e cd. sendo que o erro das tratadas aparece da mesma forma , mesmo que os númerod de dgr permanecam em sequencia correta de -90 a +90

In [ ]:
# try gpt 
# começa apartir de (Obter linhas que faltam)
# Lê o arquivo CSV em um DataFrame
df = df_cd

In [ ]:

# try gpt 
# começa apartir de (Obter linhas que faltam)
# Lê o arquivo CSV em um DataFrame
df = df_cd
#df.iloc[80:91]
#df.head(400)
# Pega as linhas acima e abaixo da linha 88
linha_acima = df.iloc[88]
linha_abaixo = df.iloc[89]


# Inicializa uma nova linha interpolada
linha_interpolada = {}

# Para cada coluna
for coluna in df.columns:
    valor_acima = linha_acima[coluna]
    valor_abaixo = linha_abaixo[coluna]

    # Tenta converter para float e fazer interpolação
    try:
        valor_interp = (float(valor_acima) + float(valor_abaixo)) / 2
    except ValueError:
        # Se não for numérico (ex: texto), coloca um valor nulo ou preserva o de cima
        valor_interp = None  # ou use: valor_acima

    linha_interpolada[coluna] = valor_interp

# Converte para DataFrame
linha_interpolada_df = pd.DataFrame([linha_interpolada])

# Insere a nova linha na posição 88
df_novo = pd.concat([df.iloc[:89], linha_interpolada_df, df.iloc[89:]]).reset_index(drop=True)
#df_novo
#df_novo.iloc[80:91]
# Salva o novo arquivo
df_novo.to_csv('arquivo_mo33dificado.csv', index=False)

print("Linha interpolada inserida com sucesso na linha 89.")

In [ ]:
## alterações em CD ( ANTIGAS A SEREM DESCARTADAS) e63

# alterar incorreto cd 9 
#import pandas as pd
# add a line between line 97 and 98 that is the same as line 97

# Supondo que 'df' é o seu DataFrame

# Separar o topo, a linha a duplicar, e o restante
top = df_cd.iloc[:99]                      # inclui até a linha 98
duplicate_row = df_cd.iloc[[98]].copy()   # linha 97 (como DataFrame)
bottom = df_cd.iloc[99:]                  # da linha 98 em diante

# Concatenar tudo
df_cd = pd.concat([top, duplicate_row, bottom]).reset_index(drop=True)
# alterar valor do grau 9 
df_cd.iloc[99, 0] = 9.0000000e+00

## 
# alterar incorreto cd 13 
#import pandas as pd
# add a line between line 97 and 98 that is the same as line 97

# Supondo que 'df' é o seu DataFrame

# Separar o topo, a linha a duplicar, e o restante
top = df_cd.iloc[:103]                      # inclui até a linha 97
duplicate_row = df_cd.iloc[[102]].copy()   # linha 97 (como DataFrame)
bottom = df_cd.iloc[103:]                  # da linha 98 em diante

# Concatenar tudo
df_cd = pd.concat([top, duplicate_row, bottom]).reset_index(drop=True)
# alterar valor do grau 9 
df_cd.iloc[103, 0] = 1.3000000e+01

##

# alterar incorreto cd 14 
#import pandas as pd
# add a line between line 97 and 98 that is the same as line 97

# Supondo que 'df' é o seu DataFrame

# Separar o topo, a linha a duplicar, e o restante
top = df_cd.iloc[:104]                      # inclui até a linha 97
duplicate_row = df_cd.iloc[[104]].copy()   # linha 97 (como DataFrame)
bottom = df_cd.iloc[104:]                  # da linha 98 em diante

# Concatenar tudo
df_cd = pd.concat([top, duplicate_row, bottom]).reset_index(drop=True)
# alterar valor do grau 9 
df_cd.iloc[104, 0] = 1.4000000e+01


# show 

df_cd.iloc[95:110]

In [ ]:
## alterações em CL ( ANTIGAS A SEREM DESCARTADAS) e63

# alterar incorreto cl 9 

# add a line between line 98 and 99 that is the same as line 98


# Separar o topo, a linha a duplicar, e o restante
top = df_cl.iloc[:99]                      # inclui até a linha 98
duplicate_row = df_cl.iloc[[98]].copy()   # linha 98 (como DataFrame)
bottom = df_cl.iloc[99:]                  # da linha 99 em diante

# Concatenar tudo  ( top + copy + botton) 
      #( linha faltante assume o valor da linha copiada,e entra no seu lugar)
df_cl = pd.concat([top, duplicate_row, bottom]).reset_index(drop=True)

# alterar valor do grau 9 
df_cl.iloc[99, 0] = 9.0000000e+00

## 
# alterar incorreto cl 13 
#import pandas as pd
# add a line between line 97 and 98 that is the same as line 97

# Supondo que 'df' é o seu DataFrame

# Separar o topo, a linha a duplicar, e o restante
top = df_cl.iloc[:103]                      # inclui até a linha 97
duplicate_row = df_cl.iloc[[102]].copy()   # linha 97 (como DataFrame)
bottom = df_cl.iloc[103:]                  # da linha 98 em diante

# Concatenar tudo
df_cl = pd.concat([top, duplicate_row, bottom]).reset_index(drop=True)
# alterar valor do grau 9 
df_cl.iloc[103, 0] = 1.3000000e+01

##

# alterar incorreto cl 14 
#import pandas as pd
# add a line between line 97 and 98 that is the same as line 97

# Supondo que 'df' é o seu DataFrame

# Separar o topo, a linha a duplicar, e o restante
top = df_cl.iloc[:104]                      # inclui até a linha 97
duplicate_row = df_cl.iloc[[104]].copy()   # linha 97 (como DataFrame)
bottom = df_cl.iloc[104:]                  # da linha 98 em diante

# Concatenar tudo
df_cl = pd.concat([top, duplicate_row, bottom]).reset_index(drop=True)
# alterar valor do grau 9 
df_cl.iloc[104, 0] = 1.4000000e+01


# show 

df_cl.iloc[95:110]

In [ ]:
# try gpt 



# Pega as linhas acima e abaixo da linha 88
linha_acima = df.iloc[87]
linha_abaixo = df.iloc[88]

# Calcula a média (interpolação linear)
linha_interpolada = (linha_acima + linha_abaixo) / 2

# Insere a nova linha no índice 88
df_parte1 = df.iloc[:88]
df_parte2 = df.iloc[88:]

# Concatena as partes com a nova linha no meio
df_novo = pd.concat([df_parte1, pd.DataFrame([linha_interpolada]), df_parte2], ignore_index=True)

# Salva de volta no CSV (sobrescrevendo)
df_novo.to_csv('arquivo_modificado.csv', index=False)

print("Linha interpolada inserida com sucesso na linha 88.")

In [ ]:
df = df_cl
if len(df) < 89:
    raise ValueError("O arquivo CSV precisa ter pelo menos 89 linhas para inserir na posição 88.")
# Pega as linhas acima e abaixo da linha 88
linha_acima = df.iloc[87]
linha_abaixo = df.iloc[88]
# Calcula a média (interpolação linear)
linha_interpolada = (linha_acima + linha_abaixo) / 2

In [ ]:
## fazer interpolação entre os valores das colunas seguintes 
#da de cima e da de baixo ao inves de coloar a de baixo ou de cima arbitratiamente 

#import pandas as pd

# Caminho do arquivo CSV
#arquivo_csv = 'arquivo_csv'

# Lê o arquivo CSV em um DataFrame
#df = pd.read_csv(arquivo_csv)
df = df_cl
# Verifica se há pelo menos 89 linhas
if len(df) < 89:
    raise ValueError("O arquivo CSV precisa ter pelo menos 89 linhas para inserir na posição 88.")

# Pega as linhas acima e abaixo da linha 88
linha_acima = df.iloc[87]
linha_abaixo = df.iloc[88]

# Calcula a média (interpolação linear)
linha_interpolada = (linha_acima + linha_abaixo) / 2

# Insere a nova linha no índice 88
df_parte1 = df.iloc[:88]
df_parte2 = df.iloc[88:]

# Concatena as partes com a nova linha no meio
df_novo = pd.concat([df_parte1, pd.DataFrame([linha_interpolada]), df_parte2], ignore_index=True)

# Salva de volta no CSV (sobrescrevendo)
df_novo.to_csv('arquivo_modificado.csv', index=False)

print("Linha interpolada inserida com sucesso na linha 88.")

In [ ]:
df_cl.iloc[95:110]

In [ ]:
# alterar incorreto cd 9 
#import pandas as pd
# add a line between line 97 and 98 that is the same as line 97

# Supondo que 'df' é o seu DataFrame

# Separar o topo, a linha a duplicar, e o restante
top = df_cd.iloc[:99]                      # inclui até a linha 97
duplicate_row = df_cd.iloc[[98]].copy()   # linha 97 (como DataFrame)
bottom = df_cl.iloc[99:]                  # da linha 98 em diante

# Concatenar tudo
df_cd = pd.concat([top, duplicate_row, bottom]).reset_index(drop=True)
# alterar valor do grau 9 
df_cd.iloc[99, 0] = 9.0000000e+00
# show 

df_cd.iloc[95:105]

In [ ]:
# template codigo de adicionar/ copiar linhas 
#import pandas as pd
# add a line between line 97 and 98 that is the same as line 97

# Supondo que 'df' é o seu DataFrame

# Separar o topo, a linha a duplicar, e o restante
top = df_cl.iloc[:99]                      # inclui até a linha 98
duplicate_row = df_cl.iloc[[98]].copy()   # linha 98 (como DataFrame)
bottom = df_cl.iloc[99:]                  # da linha 99 em diante

# Concatenar tudo
df_cl = pd.concat([top, duplicate_row, bottom]).reset_index(drop=True)
# alterar valor do grau 9 
df_cl.iloc[99, 0] = 9.0000000e+00
# show 

df_cl.iloc[95:105]

In [ ]:
import pandas as pd

# Supondo que 'df' é o seu DataFrame

# Separar o topo, a linha a duplicar, e o restante
top = df.iloc[:98]                      # inclui até a linha 97
duplicate_row = df.iloc[[97]].copy()   # linha 97 (como DataFrame)
bottom = df.iloc[98:]                  # da linha 98 em diante

# Concatenar tudo
df = pd.concat([top, duplicate_row, bottom]).reset_index(drop=True)

In [ ]:
df_cl.iloc[99, 0] = 9.0000000e+00

In [ ]:
df_cl.iloc[95:105]

In [ ]:
#corect missing values  cl 9

# Supondo que 'df' é o seu DataFrame

# Separar o topo, a linha a duplicar, e o restante
top = df_cl.iloc[:100]                      # inclui até a linha 97
duplicate_row = df_cl.iloc[[99]].copy()   # linha 97 (como DataFrame)
bottom = df_cl.iloc[100:]                  # da linha 98 em diante

# Concatenar tudo
df_cl = pd.concat([top, duplicate_row, bottom]).reset_index(drop=True)

print('done')
df_cl.iloc[99, 0] = 9.0000000e+00
#df_cl
print('done')

In [ ]:
# template codigo de adicionar/ copiar linhas 
import pandas as pd

# Supondo que 'df' é o seu DataFrame

# Separar o topo, a linha a duplicar, e o restante
top = df.iloc[:98]                      # inclui até a linha 97
duplicate_row = df.iloc[[97]].copy()   # linha 97 (como DataFrame)
bottom = df.iloc[98:]                  # da linha 98 em diante

# Concatenar tudo
df = pd.concat([top, duplicate_row, bottom]).reset_index(drop=True)

In [ ]:
#corect missing values cl 10

# Supondo que 'df' é o seu DataFrame

# Separar o topo, a linha a duplicar, e o restante
top = df_cl.iloc[:100]                      # inclui até a linha 97
duplicate_row = df_cl.iloc[[99]].copy()   # linha 97 (como DataFrame)
bottom = df_cl.iloc[100:]                  # da linha 98 em diante

# Concatenar tudo
df_cl = pd.concat([top, duplicate_row, bottom]).reset_index(drop=True)

print('done')
df_cl.iloc[100, 0] = 1.0000000e+01
#df_cl
print('done')

In [ ]:
#corect missing values  cd 8

# Supondo que 'df' é o seu DataFrame

# Separar o topo, a linha a duplicar, e o restante
top = df_cd.iloc[:98]                      # inclui até a linha 97
duplicate_row = df_cd.iloc[[97]].copy()   # linha 97 (como DataFrame)
bottom = df_cd.iloc[98:]                  # da linha 98 em diante

# Concatenar tudo
df_cd = pd.concat([top, duplicate_row, bottom]).reset_index(drop=True)

print('done')
df_cd.iloc[98, 0] = 9.0000000e+00
#df_cld
print('done')

In [ ]:
#corect missing values cd 10

# Supondo que 'df' é o seu DataFrame

# Separar o topo, a linha a duplicar, e o restante
top = df_cd.iloc[:100]                      # inclui até a linha 97
duplicate_row = df_cd.iloc[[99]].copy()   # linha 97 (como DataFrame)
bottom = df_cd.iloc[100:]                  # da linha 98 em diante

# Concatenar tudo
df_cd = pd.concat([top, duplicate_row, bottom]).reset_index(drop=True)

print('done')
df_cd.iloc[100, 0] = 1.0000000e+01
#df_cl
print('done')

In [ ]:
df_cl.iloc[95:110]

In [ ]:
df_cd.iloc[95:110]

In [ ]:
df_cd.head(190)

In [ ]:
df_cl.head(180)

In [ ]:
# Garante que pandas mostre todas as linhas e colunas sem cortar
pd.set_option('display.max_rows', None)
pd.set_option('display.max_colwidth', None)
print(df_cl.iloc[:, [0]])

In [ ]:
print(df_cl.iloc[:, [0]])

In [ ]:
print(df_cl.columns)

In [ ]:
df_cl.to_csv('cl.txt', index=False, header=False, sep='\t')
df_cd.to_csv('cd.txt', index=False, header=False, sep='\t')
print('done')

In [ ]:
#df2.to_csv('arquivo_final', index=False, header=False, sep='\t') ( de -180 a +180)
df_cl_1.to_csv('cl_plus.txt', index=False, header=False, sep='\t')
df_cd_1.to_csv('cd_pus.txt', index=False, header=False, sep='\t')

In [ ]:
# paralel test ( coment )

# Example for space- or tab-delimited files
#f = pd.read_csv('data.txt', delimiter='\t')  # or use delimiter=' ' for space

# Save as CSV
#df.to_csv('data.csv', index=False)
#"C:\Users\pedro\Downloads\Xmobots_Matlab\polares.airfoils\Clark Y\cl"
#df3.to_csv('C:/Users/pedro/Downloads/Xmobots_Matlab/polares.airfoils/Clark Y/cl/cl.txt', index=False, sep='\t')
df = pd.read_csv('/kaggle/working/cl.txt',delimiter='\t')

print(df.columns)
df.head(12)
#print('/kaggle/working/cl.txt')

## Writing to files

In [ ]:
## read and transform, line to line ( coment )


#import csv
#"C:\Users\pedro\Downloads\Xmobots_Matlab\polares.airfoils\Clark Y\cl\cl_R_2e4.txt"
# Open the .txt file and read lines
#with open('"C:\Users\pedro\Downloads\Xmobots_Matlab\polares.airfoils\Clark Y\cl\cl_R_2e4.txt"', 'r') as txt_file:
#    lines = txt_file.readlines()

# Write to a .csv file
#with open('/kaggle/input/polar-try/cl_R_2e4.txt', 'w', newline='') as csv_file:
#    writer = csv.writer(csv_file)

 #   for line in lines:
 #       row = line.strip().split()  # Change .split() to .split(',') if it's comma-separated
 #       writer.writerow(row)

In [ ]:
df2.to_csv("/kaggle/working/Combined_NOT_Flights_2022.csv", index=False)
#/kaggle/input/polar-try/cl_R_2e4.csv
#print(df2)

## Dataframe basics

In [ ]:
pd.set_option("display.max_columns", 500)

In [ ]:
df2.head(3)

In [ ]:
df2.tail(3)

In [ ]:
df2.sample(3, random_state=42)

In [ ]:
df2.sample(frac=0.000001, random_state=42)

In [ ]:
df2.columns

In [ ]:
df.index

## Dataframe summary

In [ ]:
df.info()

In [ ]:
df.info(verbose=False)

In [ ]:
df.describe()

In [ ]:
df[["Airline"]].describe()

In [ ]:
df.shape, len(df)

## Subsetting Columns

In [ ]:
df[['FlightDate', 'Airline', 'Origin']]

In [ ]:
df[df.columns[:5]]

In [ ]:
df[[c for c in df.columns if 'Time' in c]]

## Select dtypes

In [ ]:
df.select_dtypes('int')

## Select as series vs dataframe

In [ ]:
df['Airline']

In [ ]:
df[['Airline']]

## loc and iloc

In [ ]:
df.iloc[1, 3]

In [ ]:
df.iloc[:5, :5]

In [ ]:
df.iloc[[5]]

In [ ]:
df.iloc[:, 1]

In [ ]:
df.iloc[:, [1, 2]]

In [ ]:
df.loc[:, ['Airline', 'Origin']]

## loc filter expressions

In [ ]:
df.loc[df['Airline'] == 'Spirit Air Lines']

In [ ]:
df.loc[(df['Airline'] == 'Spirit Air Lines') & (df['FlightDate'] == '2022-03-30')]

In [ ]:
df.loc[~((df['Airline'] == 'Spirit Air Lines') & (df['FlightDate'] == '2022-03-30'))]

## query

In [ ]:
df.query('DepTime > 1130 and (Origin == "DRO")')

In [ ]:
# min_time = 1130
# df.query('DepTime > @min_time and (Origin == "DRO")')  # ValueError: Expression ((DepTime) > (__pd_eval_local_min_time)) & (Series_1_0x200x4c0x3a0x6c0xbf0x7d0x00x0) has forbidden control characters.

min_time = 1130
query_expression = 'DepTime > {} and (Origin == "DRO")'.format(min_time)
df.query(query_expression)

## Summary Statistics

In [ ]:
df['DepTime'].min()

In [ ]:
df['DepTime'].max()

In [ ]:
df['DepTime'].mean()

In [ ]:
df['DepTime'].std()

In [ ]:
df['DepTime'].sum()

In [ ]:
df['DepTime'].quantile(0.5)

In [ ]:
df['DepTime'].quantile([0.25, 0.75])

## agg

In [ ]:
df[['DepTime', 'DepDelay', 'ArrTime', 'ArrDelay']].agg(['mean', 'min', 'max'])

In [ ]:
df[['DepTime', 'DepDelay', 'ArrTime', 'ArrDelay']].agg(
    {
        'DepTime': ['min', 'max'],
        'DepDelay': ['mean'],
        'ArrTime': ['min', 'max']
    }
)

## Summarize categoricals

In [ ]:
df['Airline'].unique()

In [ ]:
df['Airline'].nunique()

In [ ]:
df['Airline'].value_counts()

In [ ]:
df[['Airline', 'Origin']].value_counts()

In [ ]:
df[['Airline', 'Origin']].value_counts().reset_index()

## rank, shift, cumsum

In [ ]:
df[['CRSDepTime']].rank(method='dense')

In [ ]:
df[['CRSDepTime']].rank(method='first')

In [ ]:
df[['CRSDepTime']].shift(1)

In [ ]:
df[['CRSDepTime']].shift(-1)

In [ ]:
df[['CRSDepTime']].shift(3, fill_value=100)

In [ ]:
df[['CRSDepTime']].cumsum()

In [ ]:
df[['CRSDepTime']].cummax()

In [ ]:
df[['CRSDepTime']].cummin()

## Rolling methods

In [ ]:
df[['DepDelayMinutes']].rolling(window=5).mean()

## Clip

In [ ]:
df['DepTime'].clip(1000, 2000)

## Groupby

In [ ]:
df.groupby('Airline')[['DepDelay']].mean()

In [ ]:
df.groupby('Airline')[['DepDelay']].agg(['mean', 'min', 'max'])

In [ ]:
df_agg = df.groupby('Airline')[['DepDelay', 'ArrDelay']].agg(['mean', 'min', 'max'])

In [ ]:
df_agg.columns

In [ ]:
df_agg.columns.to_flat_index()

In [ ]:
df_agg.columns = ["_".join(c) for c in df_agg.columns]

In [ ]:
df_agg

## New columns

In [ ]:
df['DepTime2'] = df['DepTime'] / 60

In [ ]:
df.head(3)

In [ ]:
df = df.assign(DepTime3 = df['DepTime'] / 60)
df.head(3)

## Sorting

In [ ]:
df.sort_values('ArrDelay')

In [ ]:
df[['FlightDate', 'Airline', 'ArrDelay']].sort_values('ArrDelay', ascending=False)

In [ ]:
df[['FlightDate', 'Airline', 'ArrDelay']].sort_values('ArrDelay', ascending=False).reset_index(drop=True)

In [ ]:
df[['FlightDate', 'Airline', 'ArrDelay']].sort_index()

## Missing data

In [ ]:
df[['FlightDate', 'Airline', 'ArrDelay']].isna()

In [ ]:
df[['FlightDate', 'Airline', 'ArrDelay']].isna().sum()

In [ ]:
df[['FlightDate', 'Airline', 'ArrDelay']].dropna(subset=['ArrDelay'])

In [ ]:
df[['FlightDate', 'Airline', 'ArrDelay']].fillna(-999)

In [ ]:
df['ArrDelay'].fillna(df['ArrDelay'].mean())

## Concat

In [ ]:
df1 = df.query('Airline == "Southwest Airlines Co."').copy()
df2 = df.query('Airline == "Delta Air Lines Inc."').copy()

In [ ]:
pd.concat([df1, df2])

In [ ]:
df_stack = pd.concat([df1, df2])

In [ ]:
df1 = df1.reset_index(drop=True)
df2 = df2.reset_index(drop=True)

In [ ]:
df_side = pd.concat([df1, df2], axis=1)

In [ ]:
df1.shape, df2.shape, df_stack.shape, df_side.shape

## Merge dataframes

In [ ]:
df1 = df.groupby(['Airline', 'FlightDate'])[['DepDelay']].mean().reset_index()
df2 = df.groupby(['Airline', 'FlightDate'])[['ArrDelay']].mean().reset_index()

In [ ]:
df2

In [ ]:
df1.merge(df2, how="left")

In [ ]:
df1.merge(df2, how="right")

In [ ]:
df1.merge(df2, how="outer")

## Merge suffixes

In [ ]:
pd.merge(df1, df2, on=['Airline', 'FlightDate'])

In [ ]:
pd.merge(df1, df2, on=['Airline'])

In [ ]:
pd.merge(df1, df2, on=['Airline'], suffixes=('_dep', '_arr'))

In [ ]:
pd.merge(df1, df2, left_on=['Airline'], right_on=['Airline'])